//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisement()
        {
            this.Image_Advertisement = new HashSet<Image_Advertisement>();
        }
    
        public int advertisiment_id { get; set; }
        public string advertisiment_companyname { get; set; }
        public string advertisiment_note { get; set; }
        public Nullable<bool> advertisiment_activate { get; set; }
        public Nullable<System.DateTime> advertisiment_dateCreate { get; set; }
        public Nullable<System.DateTime> advertisiment_dateEdit { get; set; }
        public Nullable<bool> advertisiment_recycleBin { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image_Advertisement> Image_Advertisement { get; set; }
    }
}
