//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answer()
        {
            this.Comment_Answer = new HashSet<Comment_Answer>();
            this.Rate_Answer = new HashSet<Rate_Answer>();
        }
    
        public int answer_id { get; set; }
        public string answer_content { get; set; }
        public Nullable<System.DateTime> answer_dateCreate { get; set; }
        public Nullable<System.DateTime> answer_dateEdit { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> answer_activate { get; set; }
        public Nullable<bool> answer_userStatus { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> answer_totalRate { get; set; }
        public Nullable<int> answer_medalCalculate { get; set; }
        public Nullable<bool> answer_recycleBin { get; set; }
        public Nullable<bool> answer_admin_recycleBin { get; set; }
        public Nullable<bool> answer_correct { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Answer> Comment_Answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate_Answer> Rate_Answer { get; set; }
    }
}
