//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commune
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commune()
        {
            this.Users = new HashSet<User>();
        }
    
        public int commune_id { get; set; }
        public string commune_name { get; set; }
        public Nullable<bool> commune_activate { get; set; }
        public Nullable<System.DateTime> commune_dateCreate { get; set; }
        public Nullable<System.DateTime> commune_dateEdit { get; set; }
        public Nullable<bool> commune_recycleBin { get; set; }
        public Nullable<int> district_id { get; set; }
    
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
