//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Answer
    {
        public int commentAnswer_id { get; set; }
        public string commentAnswer_content { get; set; }
        public Nullable<System.DateTime> commentAnswer_dateCreate { get; set; }
        public Nullable<System.DateTime> commentAnswer_dateEdit { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> answer_id { get; set; }
        public Nullable<bool> commentAnswer_recycleBin { get; set; }
        public Nullable<bool> commentAnswer_activate { get; set; }
        public Nullable<bool> commentAnswer_userStatus { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual User User { get; set; }
    }
}
