//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denounce_User
    {
        public int denounceUser_id { get; set; }
        public Nullable<int> accuser_id { get; set; }
        public Nullable<int> discredit_id { get; set; }
        public string denounceUser_content { get; set; }
        public Nullable<System.DateTime> denounceUser_dateCreate { get; set; }
        public Nullable<bool> denounceUser_recycleBin { get; set; }
        public Nullable<bool> denounce_viewStatus { get; set; }
        public Nullable<bool> denounce_status { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
