//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public District()
        {
            this.Communes = new HashSet<Commune>();
            this.Users = new HashSet<User>();
        }
    
        public int district_id { get; set; }
        public string district_name { get; set; }
        public Nullable<bool> district_activate { get; set; }
        public Nullable<System.DateTime> district_dateCreate { get; set; }
        public Nullable<System.DateTime> district_dateEdit { get; set; }
        public Nullable<bool> district_recycleBin { get; set; }
        public Nullable<int> provincial_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commune> Communes { get; set; }
        public virtual Provincial Provincial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
