//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        public int letters_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string letters_content { get; set; }
        public Nullable<bool> letters_status { get; set; }
        public Nullable<bool> letters_recycleBin { get; set; }
        public Nullable<System.DateTime> letters_dateCreate { get; set; }
        public Nullable<System.DateTime> letters_dateEdit { get; set; }
        public Nullable<bool> letters_statusSee { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual Role_User Role_User { get; set; }
        public virtual User User { get; set; }
    }
}
