//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letters_Idea
    {
        public int lettersIdea_id { get; set; }
        public string lettersIdea_content { get; set; }
        public Nullable<bool> lettersIdea_activate { get; set; }
        public Nullable<System.DateTime> lettersIdea_dateCreate { get; set; }
        public Nullable<System.DateTime> lettersIdea_dateEdit { get; set; }
        public Nullable<bool> lettersIdea_recycleBin { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual Role_User Role_User { get; set; }
    }
}
