//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int message_id { get; set; }
        public string message_content { get; set; }
        public Nullable<int> messageSender_id { get; set; }
        public Nullable<int> messageRecipients_id { get; set; }
        public Nullable<System.DateTime> message_dateSend { get; set; }
        public Nullable<bool> message_recycleBin { get; set; }
        public Nullable<bool> message_status { get; set; }
        public string messageRecipients_status { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
