//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notification_id { get; set; }
        public string notification_content { get; set; }
        public Nullable<int> receiver_id { get; set; }
        public Nullable<int> impactUser_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<bool> notification_status { get; set; }
        public Nullable<System.DateTime> notification_dateCreate { get; set; }
        public Nullable<bool> notification_recycleBin { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
