//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position_Advertisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position_Advertisement()
        {
            this.Image_Advertisement = new HashSet<Image_Advertisement>();
        }
    
        public int positionAdvertisement_id { get; set; }
        public string positionAdvertisement_positionName { get; set; }
        public string positionAdvertisement_note { get; set; }
        public Nullable<bool> positionAdvertisement_activate { get; set; }
        public Nullable<System.DateTime> positionAdvertisement_dateCreate { get; set; }
        public Nullable<System.DateTime> positionAdvertisement_dateEdit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image_Advertisement> Image_Advertisement { get; set; }
    }
}
