//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Rate_Post = new HashSet<Rate_Post>();
            this.View_Post = new HashSet<View_Post>();
        }
    
        public int post_id { get; set; }
        public string post_content { get; set; }
        public Nullable<System.DateTime> post_dateCreate { get; set; }
        public Nullable<System.DateTime> post_dateEdit { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> post_activate { get; set; }
        public string post_title { get; set; }
        public Nullable<int> post_view { get; set; }
        public Nullable<int> post_totalLike { get; set; }
        public Nullable<int> post_totalDislike { get; set; }
        public Nullable<bool> post_recycleBin { get; set; }
        public Nullable<bool> post_userStatus { get; set; }
        public Nullable<bool> post_admin_recycleBin { get; set; }
        public string post_image { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate_Post> Rate_Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<View_Post> View_Post { get; set; }
    }
}
