//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate_Answer
    {
        public int rateAnswer_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> answer_id { get; set; }
        public Nullable<bool> rateAnswer_rateStatus { get; set; }
        public Nullable<System.DateTime> rateAnswer_dateCreate { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual User User { get; set; }
    }
}
