//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regulation
    {
        public int regulations_id { get; set; }
        public string regulations_name { get; set; }
        public Nullable<bool> regulations_activate { get; set; }
        public Nullable<bool> regulations_recycleBin { get; set; }
        public Nullable<System.DateTime> regulations_dateCreate { get; set; }
        public Nullable<System.DateTime> regulations_dateEdit { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual Role_User Role_User { get; set; }
    }
}
