//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags_Question
    {
        public int tagsQuestion_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public string tagsQuestion_name { get; set; }
        public Nullable<System.DateTime> tagsQuestion_dateCreate { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
