//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FivePSocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technology
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Technology()
        {
            this.Teachnology_Question = new HashSet<Teachnology_Question>();
            this.Teachnology_User = new HashSet<Teachnology_User>();
        }
    
        public int technology_id { get; set; }
        public string technology_name { get; set; }
        public Nullable<int> technology_popular { get; set; }
        public Nullable<bool> technology_activate { get; set; }
        public Nullable<bool> technology_recycleBin { get; set; }
        public Nullable<System.DateTime> technology_dateCreate { get; set; }
        public Nullable<System.DateTime> technology_dateEdit { get; set; }
        public string technology_note { get; set; }
        public Nullable<int> technology_totalQuestion { get; set; }
        public string technology_img { get; set; }
        public string technology_fullname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teachnology_Question> Teachnology_Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teachnology_User> Teachnology_User { get; set; }
    }
}
